name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
  workflow_dispatch:
    branches: ["**"]

jobs:

  build:

    env: 
      ENABLE_DOCKER_PUSH: ${{ github.repository_owner == 'PlummersSoftwareLLC' && github.ref == 'refs/heads/master' }}

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Plain .NET restore and build
      run: |
        dotnet restore
        dotnet build --no-restore

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      if: ${{ env.ENABLE_DOCKER_PUSH == 'true' }}
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build amd64/arm64 Docker image
      uses: docker/build-push-action@v2
      with:
        tags: davepl/nightdriverserver:latest
        context: .
        platforms: linux/amd64,linux/arm64
        push: ${{ env.ENABLE_DOCKER_PUSH }}

    - name: Build arm32 Docker image
      uses: docker/build-push-action@v2
      with:
        tags: davepl/nightdriverserver:latest-arm32
        context: .
        file: Dockerfile.arm32
        push: ${{ env.ENABLE_DOCKER_PUSH }}
